/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.List;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.pdfbox.pdmodel.PDDocument;
import pdfmergersplitter.Constants;
import pdfmergersplitter.DocPart;
import pdfmergersplitter.Verifier;

/**
 *
 * @author Vasilis
 */
public class EditDocPartMergeFrame extends javax.swing.JFrame {
    
    //Attributes to handle frame's parameters.
    private List mergeList;
    private ArrayList<DocPart> docPartMergeList;
    private int currentIndex;
    private File documentFile;
    private PDDocument document;
    private int documentPages;
    
    //Listener to bind to buttons.
    private ButtonListener buttonListener;

    /**
     * Creates new form AddDocPartFrame
     */
    public EditDocPartMergeFrame(List inputList, ArrayList<DocPart> docPartInputList, int index) {
        initComponents();
        bindButtonListeners();
        
        mergeList = inputList;
        docPartMergeList = docPartInputList;
        currentIndex = index;
        documentPages = docPartMergeList.get(currentIndex).getSourceDocument().getNumberOfPages();
        
        displayDocPartInfo(docPartMergeList.get(currentIndex));
        
        setVisible(true);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startPageLabel = new javax.swing.JLabel();
        endPageLabel = new javax.swing.JLabel();
        filenameLabel = new javax.swing.JLabel();
        startPageField = new javax.swing.JTextField();
        endPageField = new javax.swing.JTextField();
        filenameField = new javax.swing.JTextField();
        editDocButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        allPagesCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Document");
        setResizable(false);

        startPageLabel.setText("Start page:");

        endPageLabel.setText("End page:");

        filenameLabel.setText("File name:");

        endPageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endPageFieldActionPerformed(evt);
            }
        });

        filenameField.setEditable(false);
        filenameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filenameFieldActionPerformed(evt);
            }
        });

        editDocButton.setText("Edit Doc");

        cancelButton.setText("Cancel");

        allPagesCheckBox.setText("All Pages");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(282, Short.MAX_VALUE)
                        .addComponent(editDocButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(filenameLabel)
                                .addGap(18, 18, 18)
                                .addComponent(filenameField))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(startPageLabel)
                                    .addComponent(endPageLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(allPagesCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(endPageField)
                                    .addComponent(startPageField))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startPageLabel)
                    .addComponent(startPageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endPageLabel)
                    .addComponent(endPageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(allPagesCheckBox)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filenameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filenameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editDocButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void endPageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endPageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endPageFieldActionPerformed

    private void filenameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filenameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filenameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditDocPartMergeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditDocPartMergeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditDocPartMergeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditDocPartMergeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new EditDocPartMergeFrame().setVisible(true);
            }
        });
    }
    
    //Method that binds button listener with buttons.
    private void bindButtonListeners(){
        buttonListener = new ButtonListener();
        cancelButton.addActionListener(buttonListener);
        editDocButton.addActionListener(buttonListener);
        
    }
    
    //Method that shows an error message.
    private void showMessage(String title, String message, int messageType){
        JOptionPane.showMessageDialog(this, message, title, messageType);
    }
    
    //Method that reset the field with any empty string.
    private void resetFields(){
        startPageField.setText(Constants.EMPTY_STRING);
        endPageField.setText(Constants.EMPTY_STRING);
        filenameField.setText(Constants.EMPTY_STRING);
        allPagesCheckBox.setSelected(false);
    }
    
    //Method that displays doc part information.
    private void displayDocPartInfo(DocPart docPart){
        startPageField.setText(String.valueOf(docPart.getStartPage()));
        endPageField.setText(String.valueOf(docPart.getEndPage()));
        filenameField.setText(String.valueOf(docPart.getFilename()));
    }
    
    //Listener that will respond to key presses.
    class ButtonListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent event) {
            
            if(event.getSource() == editDocButton){
                
                String startPageString = startPageField.getText();
                String endPageString = endPageField.getText();
                String filenameString = filenameField.getText();
                
                boolean startPageVerify = Verifier.verifyNumericInput(startPageString);
                boolean endPageVerify = Verifier.verifyNumericInput(endPageString);
                boolean filenameVerify = Verifier.verifyFilenameInput(filenameString);
                                
                if(!startPageVerify || !endPageVerify || !filenameVerify){
                    showMessage(Constants.ERROR_TITLE, Constants.INVALID_TEXT_FIELD_VALUE_MESSAGE, Constants.ERROR_MESSAGE);
                    resetFields();
                }
                else{
                    Integer startPage = Integer.parseInt(startPageString);
                    Integer endPage = Integer.parseInt(endPageString);
                    
                    if(!Verifier.arePageIndicesValid(startPage, endPage, documentPages)){
                        showMessage(Constants.ERROR_TITLE, Constants.INVALID_START_AND_END_PAGE_INDICES_MESSAGE, Constants.ERROR_MESSAGE);
                        resetFields();
                    }
                    else{
                        DocPart docPart = docPartMergeList.get(currentIndex);
                        docPart.setStartPage(startPage);
                        docPart.setEndPage(endPage);
                        
                        docPartMergeList.set(currentIndex, docPart);
                        mergeList.replaceItem(docPart.toString(), currentIndex);
                        
                        displayDocPartInfo(docPart);
                        showMessage(Constants.INFO_TITLE, Constants.DOC_PART_EDITED, Constants.INFO_MESSAGE);
                    }
                }
            }
          
            if(event.getSource() == cancelButton){
                dispose();
            }
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox allPagesCheckBox;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton editDocButton;
    private javax.swing.JTextField endPageField;
    private javax.swing.JLabel endPageLabel;
    private javax.swing.JTextField filenameField;
    private javax.swing.JLabel filenameLabel;
    private javax.swing.JTextField startPageField;
    private javax.swing.JLabel startPageLabel;
    // End of variables declaration//GEN-END:variables
}
